added function
js-tasks-ru/js-20201211_artem416 pull request #2
Opened 2020-12-16 18:58 UTC by dontshoot11

2020-12-16 20:25 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-12-17 19:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-17 23:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        let fN = first.normalize(),
в данной задаче нет необходимости нормализовывать строки

2020-12-17 23:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        return newArr.sort(smartSort).reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2020-12-17 23:26 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +            delete answer[[fields[i]]];
удаление данных из объектов крайне нежелательно, но это обсудим на следующем занятии

2020-12-17 23:26 UTC, dosandk requested changes
необходимо внести правки в решение `sortStrings`

2020-12-18 08:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-18 15:08 UTC, dosandk approved these changes

2020-12-18 15:08 UTC, merged