добавлено решение 4 задач
js-tasks-ru/js-20201211_artem416 pull request #3
Opened 2020-12-20 12:38 UTC by dontshoot11

2020-12-20 12:44 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-12-20 13:06 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +            const pathArr = path.split(".");
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2020-12-20 13:07 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        if (Object.keys(obj).length != 0) {
помните что нет такого оператора `!=` в Javascript

2020-12-20 13:08 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +            for (let i = 0; i < pathArr.length; i++) {
более удобный метод итерации по массивам: `forEach` либо `for...of`
подробнее можно почитать вот тут https://jstips.space/loops/

2020-12-20 13:09 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    return Array.from(new Set(arr));
подумайте в чем преимущество метода `Array.from` по сравнению с `...` - спред синтаксисом:
```
return [...new Set(arr)]
```

2020-12-20 13:18 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
>  export function trimSymbols(string, size) {
очень хорошее решение

2020-12-20 13:19 UTC, dosandk requested changes
нужн внести правки в решение `createGetter`

2020-12-20 16:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-22 12:05 UTC, dosandk approved these changes
good 👍

2020-12-22 12:06 UTC, merged