ColumnChart add
js-tasks-ru/js-20201211_artem416 pull request #4
Opened 2020-12-26 12:29 UTC by dontshoot11

2020-12-26 12:36 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-12-27 16:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-28 09:30 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    append(target) {
здесь будет удобно задать параметр по умолчанию, это позволит избавиться от тернарника:
```
append(target = document.body) {
  target.append(this.element)
}
```

2020-12-28 09:31 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        let notification = document.querySelector(".notification");
помните на занятии я говорил что не стоит лишний раз обращаться к DOM. Подумайте может есть способ как-то по другому проверить что нотификейшен сейчас показывается?

2020-12-28 09:32 UTC, dosandk requested changes
необходимо внести правки в решение `Notification`

2020-12-30 07:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-30 09:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-30 21:35 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +            headerTemplate += `    <div class="sortable-table__cell" data-id="${
на занятии я говорил что лучше использовать подход с `map` для формирования тимплейта вместо конкатенации строк. Помните почему?

2020-12-30 21:35 UTC, dosandk approved these changes
good 👍

2020-12-30 21:36 UTC, merged